apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: my-laravel-db
  name: my-laravel-db
  namespace: myapp
spec:
  serviceAccountName: ebs-csi-controller-sa3
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
