apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: my-laravel-app
  name: my-laravel-app
  namespace: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: my-laravel-app
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: my-laravel-app
    spec:
      containers:
        - image: dharnel/laravelapp:7.1
          name: my-laravel-app
          ports:
            - containerPort: 80
#          livenessProbe:
#            httpGet:
#              path: /healthz
#              port: 80
#              httpHeaders:
#               - name: Custom-Header
#                 value: Awesome
#            initialDelaySeconds: 3
#            periodSeconds: 3
          resources: {}
          volumeMounts:
            - mountPath: /var/www/html
              name: my-laravel-app1
              subPath: html
            - mountPath: /var/www/laravel-realworld-example-app/vendor/
              name: my-laravel-app
              subPath: laravel-realworld-example-app
      restartPolicy: Always
      volumes:
        - name: my-laravel-app1
          emptyDir:
            medium: Memory
        - name: my-laravel-app
          emptyDir:
            medium: Memory
status: {}
