pipeline {
    agent any
    environment {
        AWS_ACCESS_KEY_ID = credentials('AWS_ACCESS_KEY_ID')
        AWS_SECRET_ACCESS_KEY = credentials('AWS_SECRET_ACCESS_KEY')
        AWS_DEFAULT_REGION = "eu-west-2"
    }
    stages {
        stage("Initialize terraform") {
            steps {
                script {
                    dir('Deployment/terraform') {
                        sh "terraform init"
                    }
                }
            }
        }
        
        stage('Create an EKS Cluster'){
            steps{
                withAWS(credentials: 'ilab-aws', region: 'eu-west-2') {
                script {
                    dir('Deployment/terraform') {
                        sh 'terraform destroy --auto-approve -lock=false'
                    }
                }
                }
            }
        }
        
        }
    }

