apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: le-crt
  namespace: monitoring
spec:
  secretName: tls-secret
  issuerRef:
    kind: Issuer
    name: letsencrypt-prod
  commonName: "*.niellaravelapp.me"
  dnsNames:
    - "*.niellaravelapp.me"
