---
apiVersion: v1
kind: Namespace
metadata:
  name: myapp
---
apiVersion: v1
kind: Secret
metadata:
 name: mysql-secret
 namespace: myapp
type: Opaque
data:
 mysql-password: 4oCYcGFzc3dvcmTigJk=
 mysql-root-password: 4oCYcGFzc3dvcmTigJk=



